CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AdminUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AdminUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "BlogPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Slug" text NOT NULL,
    "PublishedDate" timestamp with time zone NOT NULL,
    "IsPublished" boolean NOT NULL,
    CONSTRAINT "PK_BlogPosts" PRIMARY KEY ("Id")
);

CREATE TABLE "Educations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Degree" text NOT NULL,
    "Institution" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Educations" PRIMARY KEY ("Id")
);

CREATE TABLE "Experiences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Role" text NOT NULL,
    "Company" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "Description" text NOT NULL,
    "IsCurrent" boolean NOT NULL,
    CONSTRAINT "PK_Experiences" PRIMARY KEY ("Id")
);

CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Subject" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "GithubUrl" text NOT NULL,
    "LiveDemoUrl" text NOT NULL,
    "TechStack" text NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "Skills" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "ProficiencyPercentage" integer NOT NULL,
    "Icon" text NOT NULL,
    CONSTRAINT "PK_Skills" PRIMARY KEY ("Id")
);

CREATE TABLE "Visitors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IpAddress" text NOT NULL,
    "UserAgent" text NOT NULL,
    "VisitedAt" timestamp with time zone NOT NULL,
    "PageVisited" text NOT NULL,
    CONSTRAINT "PK_Visitors" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_AdminUsers_Username" ON "AdminUsers" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260221170818_InitialCreate', '9.0.0');

CREATE TABLE "Profiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "Title" text NOT NULL,
    "Bio" text NOT NULL,
    "Tagline" text,
    "Email" text,
    "Phone" text,
    "Location" text,
    "ProfileImageUrl" text,
    "GithubUrl" text,
    "LinkedinUrl" text,
    "TwitterUrl" text,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222073001_AddProfileTable', '9.0.0');

COMMIT;

