CREATE TABLE "Profiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "Title" text NOT NULL,
    "Bio" text NOT NULL,
    "Tagline" text,
    "Email" text,
    "Phone" text,
    "Location" text,
    "ProfileImageUrl" text,
    "GithubUrl" text,
    "LinkedinUrl" text,
    "TwitterUrl" text,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222073001_AddProfileTable', '9.0.0');
